### ISSUE TITLE
Support for newer JEP-229 format

### ISSUE THREAD

**Issue by timja** [jenkinsci/plugin-compat-tester#340]
See https://github.com/jenkinsci/incrementals-tools/pull/24#issuecomment-1007685091

fyi @jglick 

Noticed in https://github.com/jenkinsci/bom/pull/859

**Comment by jglick** [comment]
> https://github.com/jenkinsci/plugin-compat-tester/blob/5a86f00cbbbba4e2c7dcb63f75538c8765e24e96/plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java#L126-L127 needs to be adjusted as well in order for recent core incrementals to work with PCT
