### ISSUE TITLE
Update to Java 11

### ISSUE THREAD

**Issue by jglick** [jenkinsci/plugin-compat-tester#390]
https://github.com/jenkinsci/plugin-compat-tester/pull/389 failed with

```
Restricted to JDK 8 yet org.jenkins-ci:version-number:jar:1.11:compile contains hudson/util/VersionNumber$ListItem.class targeted to JDK 11
```

Perhaps @basil has something in preparation to update this repo to 11 along with other parts of the toolchain? On the other hand, PCT should be able to run on JDK 11 while still testing plugins with older baselines, so updating it is probably an independent project. From a quick glance, https://github.com/jenkinsci/plugin-compat-tester/blob/b2c7632aa27b32eeb65fac973dba550b8172fdec/pom.xml#L7 is super old and so is https://github.com/jenkinsci/plugin-compat-tester/blob/b2c7632aa27b32eeb65fac973dba550b8172fdec/Jenkinsfile#L21 and https://github.com/jenkinsci/plugin-compat-tester/blob/b2c7632aa27b32eeb65fac973dba550b8172fdec/Dockerfile#L40 and https://github.com/jenkinsci/plugin-compat-tester/blob/b2c7632aa27b32eeb65fac973dba550b8172fdec/Makefile#L12 etc.

**Comment by basil** [comment]
#392
