### ISSUE TITLE
Remove `-storeAll` option

### ISSUE THREAD

**Issue by basil** [jenkinsci/plugin-compat-tester#429]
Even though CloudBees appears to use `-storeAll` I cannot see a good reason why anyone would _want_ to use it. @imonteroperez @jtnord Is there a reason we want to keep this option or can we rip it out?

**Comment by basil** [comment]
Gentle ping, any reason to keep this option?

**Comment by jtnord** [comment]
I'm not sure we use the PCT report at all, rather we use the `maven-surefire` reports and then mark the stages as unstable based on that.
