### ISSUE TITLE
since #473 docker ci status fails

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/plugin-compat-tester#479]
### Jenkins and plugins versions report

<details>
  <summary>this repo</summary>

  
  ```text
ci/dockercloud-stage — Your image failed to build in Docker Hub
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

look at commit status' for anything filed since #473 was merged.

notice they have a failing check `ci/dockercloud-stage — Your image failed to build in Docker Hub`

whilst it may be co-incidental with the timing of the removal of the docker bits - I am not sure what docker could try and build without it.

The actual check error is `{"error": "Our service is temporarily unavailable. We'll be back soon!"}`

but either we should not be merging with this failing check as it is important - or we shouldn;t bother running it 

### Expected Results

all checks for PRs pass if the code is OK

### Actual Results

one failing check even if the PR is good.

### Anything else?

I have no idea where this integration is performed

**Comment by jtnord** [comment]
https://hub.docker.com/r/jenkins/pct landing page has been updated - @basil have you disable this integration?

**Comment by lemeurherve** [comment]
@jtnord it has been disabled indeed, see https://github.com/jenkins-infra/helpdesk/issues/3417
