### ISSUE TITLE
JaCoCo hook no longer runs

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/plugin-compat-tester#490]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

Plugin hooks are not run as the code is checking incorrect data (pom) that is not fully populated.

  
  ```text

  ```

</details>

The maven model is a minimal representation of the actual pom and is both brittle and incomplete.

As mentioned in https://github.com/jenkinsci/plugin-compat-tester/pull/486#discussion_r1127574784 

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

create a war with containing jacoco

run the PCT Tests

### Expected Results

all jacoco tests pass (and the jacoco hook is run correctly)

### Actual Results

the tests fail as the jacoco hook is not excersized and does not add `jacoco:prepare-agent` to the mvn arguments when adding tests.

`ExecutionFileLoaderTest.testLoadBundleWithExecFile` and a few others require a jacoco file which is provided when running the tests.

### Anything else?

possibly affects all other plugins as well that are not using incrementals (that would inline the parent groupId) (e.g. BlueOcean) as well as potential plugins that are but are to be tested locally

**Comment by basil** [comment]
This was actually fixed in https://github.com/jenkinsci/jacoco-plugin/pull/206 but in the meantime I will work around the regression by removing the check for `groupId`. That should get the hook to pass against https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/jacoco/3.3.2/jacoco-3.3.2.pom.
