### ISSUE TITLE
Remove workarounds introduced in #510

### ISSUE THREAD

**Issue by basil** [jenkinsci/plugin-compat-tester#562]
#510 introduced a large amount of temporary code which ought to be deleted once plugins have been adapted accordingly.

**Comment by basil** [comment]
@jtnord Why was this ticket closed?

**Comment by jtnord** [comment]
because the workarounds have all been removed.

**Comment by jtnord** [comment]
Oh this was not about the git workarounds but the multi-module hooks - that was unclear.

**Comment by jtnord** [comment]
is this specifically for [`LegacyPluginMetadataExtraction`](https://github.com/jenkinsci/plugin-compat-tester/blob/43076c54d001ead03bb97b0aa0d239c73ccaac8b/src/main/java/org/jenkins/tools/test/model/plugin_metadata/LegacyPluginMetadataExtractor.java) and [code like this](https://github.com/jenkinsci/plugin-compat-tester/blob/43076c54d001ead03bb97b0aa0d239c73ccaac8b/src/main/java/org/jenkins/tools/test/util/WarExtractor.java#L145-L149) or something else?

**Comment by basil** [comment]
Yes, exactly.
